### ISSUE TITLE
Possible undefined behavior in `add_cache`

### ISSUE THREAD

**Issue by ianprime0509** [ianprime0509/pbnsolve#1]
Running `pbnsolve 26325.pbn` (using puzzle 26325 from webpbn.com) results in the following error when `pbnsolve` is compiled in debug mode. The error goes away when using `ReleaseFast`, indicating it's probably some sort of undefined behavior.

```
Program received signal SIGILL, Illegal instruction.
0x0000000000272bc0 in add_cache (puz=0x842ce0, sol=0x84bd60, k=0 '\000', i=1)
    at /home/ian/src/pbnsolve/src/line_cache.c:433
433             compress_line(puz, sol, k, i, ncell, newstate(cache[k],e));
```

Backtrace:

```
#0  0x0000000000272bc0 in add_cache (puz=0x842ce0, sol=0x84bd60, k=0 '\000', i=1)
    at /home/ian/src/pbnsolve/src/line_cache.c:433
#1  0x00000000002862e6 in apply_lro (puz=0x842ce0, sol=0x84bd60, k=0 '\000', i=1, depth=1)
    at /home/ian/src/pbnsolve/src/line_lro.c:1727
#2  0x00000000008331a1 in line_solve (puz=0x842ce0, sol=0x84bd60, contradicting=0)
    at /home/ian/src/pbnsolve/src/solve.c:92
#3  0x00000000008332c6 in logic_solve (puz=0x842ce0, sol=0x84bd60, contradicting=0)
    at /home/ian/src/pbnsolve/src/solve.c:127
#4  0x000000000028dc1e in probe_cell (puz=0x842ce0, sol=0x84bd60, cell=0xa002c0, i=1, j=76, 
    bestnleft=0x7fffffffd2f4, bestc=0x7fffffffd403 "") at /home/ian/src/pbnsolve/src/probe.c:131
#5  0x000000000028fcad in probe (puz=0x842ce0, sol=0x84bd60, besti=0x7fffffffd406, bestj=0x7fffffffd404, 
    bestc=0x7fffffffd403 "") at /home/ian/src/pbnsolve/src/probe.c:365
#6  0x00000000008339e2 in solve (puz=0x842ce0, sol=0x84bd60) at /home/ian/src/pbnsolve/src/solve.c:244
#7  0x000000000028bfa4 in main (argc=2, argv=0x7fffffffdae8) at /home/ian/src/pbnsolve/src/pbnsolve.c:563
```

<details>
<summary>Valgrind output</summary>

```
==162350== Conditional jump or move depends on uninitialised value(s)
==162350==    at 0x833179: line_solve (solve.c:92)
==162350==    by 0x8332C5: logic_solve (solve.c:127)
==162350==    by 0x8337D8: solve (solve.c:194)
==162350==    by 0x28BFA3: main (pbnsolve.c:563)
==162350== 
==162350== Conditional jump or move depends on uninitialised value(s)
==162350==    at 0x263B02: add_job (job.c:133)
==162350==    by 0x26515B: add_jobs (job.c:208)
==162350==    by 0x286292: apply_lro (line_lro.c:1717)
==162350==    by 0x8331A0: line_solve (solve.c:92)
==162350==    by 0x8332C5: logic_solve (solve.c:127)
==162350==    by 0x8337D8: solve (solve.c:194)
==162350==    by 0x28BFA3: main (pbnsolve.c:563)
==162350== 
==162350== Conditional jump or move depends on uninitialised value(s)
==162350==    at 0x264090: add_job (job.c:145)
==162350==    by 0x26515B: add_jobs (job.c:208)
==162350==    by 0x286292: apply_lro (line_lro.c:1717)
==162350==    by 0x8331A0: line_solve (solve.c:92)
==162350==    by 0x8332C5: logic_solve (solve.c:127)
==162350==    by 0x8337D8: solve (solve.c:194)
==162350==    by 0x28BFA3: main (pbnsolve.c:563)
==162350== 
==162350== Conditional jump or move depends on uninitialised value(s)
==162350==    at 0x2640B6: add_job (job.c:145)
==162350==    by 0x26515B: add_jobs (job.c:208)
==162350==    by 0x286292: apply_lro (line_lro.c:1717)
==162350==    by 0x8331A0: line_solve (solve.c:92)
==162350==    by 0x8332C5: logic_solve (solve.c:127)
==162350==    by 0x8337D8: solve (solve.c:194)
==162350==    by 0x28BFA3: main (pbnsolve.c:563)
==162350== 
==162350== Conditional jump or move depends on uninitialised value(s)
==162350==    at 0x264386: add_job (job.c:154)
==162350==    by 0x26515B: add_jobs (job.c:208)
==162350==    by 0x286292: apply_lro (line_lro.c:1717)
==162350==    by 0x8331A0: line_solve (solve.c:92)
==162350==    by 0x8332C5: logic_solve (solve.c:127)
==162350==    by 0x8337D8: solve (solve.c:194)
==162350==    by 0x28BFA3: main (pbnsolve.c:563)
==162350== 
==162350== Conditional jump or move depends on uninitialised value(s)
==162350==    at 0x26330F: heapify_jobs (job.c:100)
==162350==    by 0x2662A6: next_job (job.c:242)
==162350==    by 0x832D07: line_solve (solve.c:65)
==162350==    by 0x8332C5: logic_solve (solve.c:127)
==162350==    by 0x8337D8: solve (solve.c:194)
==162350==    by 0x28BFA3: main (pbnsolve.c:563)
==162350== 
==162350== Conditional jump or move depends on uninitialised value(s)
==162350==    at 0x26330F: heapify_jobs (job.c:100)
==162350==    by 0x26360A: heapify_jobs (job.c:108)
==162350==    by 0x2662A6: next_job (job.c:242)
==162350==    by 0x832D07: line_solve (solve.c:65)
==162350==    by 0x8332C5: logic_solve (solve.c:127)
==162350==    by 0x8337D8: solve (solve.c:194)
==162350==    by 0x28BFA3: main (pbnsolve.c:563)
==162350== 
==162350== Conditional jump or move depends on uninitialised value(s)
==162350==    at 0x26330F: heapify_jobs (job.c:100)
==162350==    by 0x26360A: heapify_jobs (job.c:108)
==162350==    by 0x26360A: heapify_jobs (job.c:108)
==162350==    by 0x2662A6: next_job (job.c:242)
==162350==    by 0x832D07: line_solve (solve.c:65)
==162350==    by 0x8332C5: logic_solve (solve.c:127)
==162350==    by 0x8337D8: solve (solve.c:194)
==162350==    by 0x28BFA3: main (pbnsolve.c:563)
==162350== 
==162350== Conditional jump or move depends on uninitialised value(s)
==162350==    at 0x26330F: heapify_jobs (job.c:100)
==162350==    by 0x26360A: heapify_jobs (job.c:108)
==162350==    by 0x26360A: heapify_jobs (job.c:108)
==162350==    by 0x26360A: heapify_jobs (job.c:108)
==162350==    by 0x2662A6: next_job (job.c:242)
==162350==    by 0x832D07: line_solve (solve.c:65)
==162350==    by 0x8332C5: logic_solve (solve.c:127)
==162350==    by 0x8337D8: solve (solve.c:194)
==162350==    by 0x28BFA3: main (pbnsolve.c:563)
==162350== 
==162350== Conditional jump or move depends on uninitialised value(s)
==162350==    at 0x2639C8: add_job (job.c:132)
==162350==    by 0x26515B: add_jobs (job.c:208)
==162350==    by 0x286292: apply_lro (line_lro.c:1717)
==162350==    by 0x8331A0: line_solve (solve.c:92)
==162350==    by 0x8332C5: logic_solve (solve.c:127)
==162350==    by 0x8337D8: solve (solve.c:194)
==162350==    by 0x28BFA3: main (pbnsolve.c:563)
==162350== 
==162350== Conditional jump or move depends on uninitialised value(s)
==162350==    at 0x263ECF: add_job (job.c:135)
==162350==    by 0x26515B: add_jobs (job.c:208)
==162350==    by 0x286292: apply_lro (line_lro.c:1717)
==162350==    by 0x8331A0: line_solve (solve.c:92)
==162350==    by 0x8332C5: logic_solve (solve.c:127)
==162350==    by 0x8337D8: solve (solve.c:194)
==162350==    by 0x28BFA3: main (pbnsolve.c:563)
==162350== 
==162350== Conditional jump or move depends on uninitialised value(s)
==162350==    at 0x2635D8: heapify_jobs (job.c:102)
==162350==    by 0x26360A: heapify_jobs (job.c:108)
==162350==    by 0x26360A: heapify_jobs (job.c:108)
==162350==    by 0x26360A: heapify_jobs (job.c:108)
==162350==    by 0x26360A: heapify_jobs (job.c:108)
==162350==    by 0x26360A: heapify_jobs (job.c:108)
==162350==    by 0x2662A6: next_job (job.c:242)
==162350==    by 0x832D07: line_solve (solve.c:65)
==162350==    by 0x8332C5: logic_solve (solve.c:127)
==162350==    by 0x8337D8: solve (solve.c:194)
==162350==    by 0x28BFA3: main (pbnsolve.c:563)
==162350== 
==162350== Conditional jump or move depends on uninitialised value(s)
==162350==    at 0x2635D8: heapify_jobs (job.c:102)
==162350==    by 0x26360A: heapify_jobs (job.c:108)
==162350==    by 0x26360A: heapify_jobs (job.c:108)
==162350==    by 0x2662A6: next_job (job.c:242)
==162350==    by 0x832D07: line_solve (solve.c:65)
==162350==    by 0x8332C5: logic_solve (solve.c:127)
==162350==    by 0x8337D8: solve (solve.c:194)
==162350==    by 0x28BFA3: main (pbnsolve.c:563)
==162350== 
==162350== Conditional jump or move depends on uninitialised value(s)
==162350==    at 0x2635D8: heapify_jobs (job.c:102)
==162350==    by 0x26360A: heapify_jobs (job.c:108)
==162350==    by 0x2662A6: next_job (job.c:242)
==162350==    by 0x832D07: line_solve (solve.c:65)
==162350==    by 0x8332C5: logic_solve (solve.c:127)
==162350==    by 0x8337D8: solve (solve.c:194)
==162350==    by 0x28BFA3: main (pbnsolve.c:563)
==162350== 
==162350== Conditional jump or move depends on uninitialised value(s)
==162350==    at 0x2635D8: heapify_jobs (job.c:102)
==162350==    by 0x2662A6: next_job (job.c:242)
==162350==    by 0x832D07: line_solve (solve.c:65)
==162350==    by 0x8332C5: logic_solve (solve.c:127)
==162350==    by 0x8337D8: solve (solve.c:194)
==162350==    by 0x28BFA3: main (pbnsolve.c:563)
==162350== 
vex amd64->IR: unhandled instruction bytes: 0x67 0xF 0xB9 0x40 0x12 0x48 0x8B 0xB5 0xC8 0xFD
vex amd64->IR:   REX=0 REX.W=0 REX.R=0 REX.X=0 REX.B=0
vex amd64->IR:   VEX=0 VEX.L=0 VEX.nVVVV=0x0 ESC=0F
vex amd64->IR:   PFX.66=0 PFX.F2=0 PFX.F3=0
==162350== valgrind: Unrecognised instruction at address 0x272bc0.
==162350==    at 0x272BC0: add_cache (line_cache.c:433)
==162350==    by 0x2862E5: apply_lro (line_lro.c:1727)
==162350==    by 0x8331A0: line_solve (solve.c:92)
==162350==    by 0x8332C5: logic_solve (solve.c:127)
==162350==    by 0x28DC1D: probe_cell (probe.c:131)
==162350==    by 0x28FCAC: probe (probe.c:365)
==162350==    by 0x8339E1: solve (solve.c:244)
==162350==    by 0x28BFA3: main (pbnsolve.c:563)
==162350== Your program just tried to execute an instruction that Valgrind
==162350== did not recognise.  There are two possible reasons for this.
==162350== 1. Your program has a bug and erroneously jumped to a non-code
==162350==    location.  If you are running Memcheck and you just saw a
==162350==    warning about a bad jump, it's probably your program's fault.
==162350== 2. The instruction is legitimate but Valgrind doesn't handle it,
==162350==    i.e. it's Valgrind's fault.  If you think this is the case or
==162350==    you are not sure, please let us know and we'll try to fix it.
==162350== Either way, Valgrind will now raise a SIGILL signal which will
==162350== probably kill your program.
==162350== 
==162350== Process terminating with default action of signal 4 (SIGILL): dumping core
==162350==  Illegal opcode at address 0x272BC0
==162350==    at 0x272BC0: add_cache (line_cache.c:433)
==162350==    by 0x2862E5: apply_lro (line_lro.c:1727)
==162350==    by 0x8331A0: line_solve (solve.c:92)
==162350==    by 0x8332C5: logic_solve (solve.c:127)
==162350==    by 0x28DC1D: probe_cell (probe.c:131)
==162350==    by 0x28FCAC: probe (probe.c:365)
==162350==    by 0x8339E1: solve (solve.c:244)
==162350==    by 0x28BFA3: main (pbnsolve.c:563)
==162350== 
==162350== HEAP SUMMARY:
==162350==     in use at exit: 6,964,900 bytes in 21,973 blocks
==162350==   total heap usage: 42,681 allocs, 20,708 frees, 8,954,499 bytes allocated
==162350== 
==162350== LEAK SUMMARY:
==162350==    definitely lost: 278,357 bytes in 6,821 blocks
==162350==    indirectly lost: 0 bytes in 0 blocks
==162350==      possibly lost: 0 bytes in 0 blocks
==162350==    still reachable: 6,686,543 bytes in 15,152 blocks
==162350==         suppressed: 0 bytes in 0 blocks
==162350== Rerun with --leak-check=full to see details of leaked memory
==162350== 
==162350== Use --track-origins=yes to see where uninitialised values come from
==162350== For lists of detected and suppressed errors, rerun with: -s
==162350== ERROR SUMMARY: 22514 errors from 15 contexts (suppressed: 0 from 0)
```

</details>

**Comment by ianprime0509** [comment]
When compiled using Clang with just `-fsanitize=undefined`, the output provides additional information:
```
line_cache.c:433:39: runtime error: index 8 out of bounds for type 'unsigned long[2]'
line_cache.c:326:7: runtime error: index 2 out of bounds for type 'unsigned long[2]'
line_cache.c:388:18: runtime error: index 6 out of bounds for type 'unsigned long[2]'
```
